import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Log;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.security.KeyStore;
import java.security.SecureRandom;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;

public class FileEncryption {
    private static final String TAG = "ENC";
    private static final String KEYSTORE_ALIAS = "FileEncryptionKey";
    private static final String ANDROID_KEYSTORE = "AndroidKeyStore";
    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final int GCM_IV_LENGTH = 12;
    private static final int GCM_TAG_LENGTH = 128;

    public static void encryptFile(String password, String filesDir) {
        try {
            String inputPath = filesDir + "/secret.txt";
            String outputPath = filesDir + "/secret.enc";

            Log.i(TAG, "Input path: " + inputPath);
            Log.i(TAG, "Output path: " + outputPath);

            // Read input file
            File inputFile = new File(inputPath);
            if (!inputFile.exists()) {
                Log.e(TAG, "Input file does not exist: " + inputPath);
                return;
            }

            byte[] fileContent = new byte[(int) inputFile.length()];
            FileInputStream fis = new FileInputStream(inputFile);
            fis.read(fileContent);
            fis.close();

            // Generate or retrieve key from Android Keystore
            SecretKey secretKey = getOrCreateKey();

            // Log all keystore aliases after key creation
            logKeystoreAliases();

            // Initialize cipher for encryption (let Keystore generate IV)
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);

            // Encrypt the file content
            byte[] encryptedData = cipher.doFinal(fileContent);

            // Get the IV that was generated by the Keystore
            byte[] iv = cipher.getIV();

            // Write IV + encrypted data to output file
            FileOutputStream fos = new FileOutputStream(outputPath);
            fos.write(iv);
            fos.write(encryptedData);
            fos.close();

            Log.i(TAG, "File encrypted successfully: " + outputPath);
            Log.i(TAG, "Key alias used: " + KEYSTORE_ALIAS);
            Log.i(TAG, "IV (hex): " + bytesToHex(iv));
            Log.i(TAG, "IV length: " + iv.length + " bytes");

        } catch (Exception e) {
            Log.e(TAG, "Encryption failed", e);
        }
    }

    private static SecretKey getOrCreateKey() throws Exception {
        KeyStore keyStore = KeyStore.getInstance(ANDROID_KEYSTORE);
        keyStore.load(null);

        // Check if key already exists
        if (keyStore.containsAlias(KEYSTORE_ALIAS)) {
            return (SecretKey) keyStore.getKey(KEYSTORE_ALIAS, null);
        }

        // Generate new key in Android Keystore
        KeyGenerator keyGenerator = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                ANDROID_KEYSTORE
        );

        KeyGenParameterSpec keySpec = new KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT
        )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build();

        keyGenerator.init(keySpec);
        return keyGenerator.generateKey();
    }

    public static void decryptFile(String filesDir) {
        try {
            Log.i(TAG, "Starting decryption...");
            String inputPath = filesDir + "/secret.enc";
            String outputPath = filesDir + "/secret_decrypted.txt";

            // Read encrypted file
            File inputFile = new File(inputPath);
            if (!inputFile.exists()) {
                Log.e(TAG, "Encrypted file does not exist: " + inputPath);
                return;
            }

            byte[] fileContent = new byte[(int) inputFile.length()];
            FileInputStream fis = new FileInputStream(inputFile);
            fis.read(fileContent);
            fis.close();

            // Extract IV and encrypted data
            byte[] iv = new byte[GCM_IV_LENGTH];
            System.arraycopy(fileContent, 0, iv, 0, GCM_IV_LENGTH);

            byte[] encryptedData = new byte[fileContent.length - GCM_IV_LENGTH];
            System.arraycopy(fileContent, GCM_IV_LENGTH, encryptedData, 0, encryptedData.length);

            Log.i(TAG, "IV (hex): " + bytesToHex(iv));

            // Get key from keystore
            SecretKey secretKey = getOrCreateKey();
            Log.i(TAG, "Key alias used: " + KEYSTORE_ALIAS);

            // Initialize cipher for decryption
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            GCMParameterSpec spec = new GCMParameterSpec(GCM_TAG_LENGTH, iv);
            cipher.init(Cipher.DECRYPT_MODE, secretKey, spec);

            // Decrypt the data
            byte[] decryptedData = cipher.doFinal(encryptedData);

            // Write decrypted data to output file
            FileOutputStream fos = new FileOutputStream(outputPath);
            fos.write(decryptedData);
            fos.close();

            Log.i(TAG, "File decrypted successfully: " + outputPath);
            Log.i(TAG, "Decrypted content: " + new String(decryptedData));

        } catch (Exception e) {
            Log.e(TAG, "Decryption failed", e);
        }
    }

    private static void logKeystoreAliases() {
        try {
            KeyStore keyStore = KeyStore.getInstance(ANDROID_KEYSTORE);
            keyStore.load(null);

            Log.i(TAG, "=== Keystore Aliases ===");
            java.util.Enumeration<String> aliases = keyStore.aliases();
            int count = 0;
            while (aliases.hasMoreElements()) {
                String alias = aliases.nextElement();
                count++;
                Log.i(TAG, "Alias " + count + ": " + alias);
            }
            Log.i(TAG, "Total aliases: " + count);
            Log.i(TAG, "========================");
        } catch (Exception e) {
            Log.e(TAG, "Failed to list keystore aliases", e);
        }
    }

    private static String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
}
